// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BandAutocompleteController from "./band_autocomplete_controller"
application.register("band-autocomplete", BandAutocompleteController)

import GlobalSearchController from "./global_search_controller"
application.register("global-search", GlobalSearchController)

import VenueAutocompleteController from "./venue_autocomplete_controller"
application.register("venue-autocomplete", VenueAutocompleteController)
